DROP TABLE VIDEO;
DROP TABLE CHANNEL;
DROP TABLE MEMBER;
DROP TABLE COMMENT;
DROP TABLE VIDEO_LIKE;
DROP TABLE SUBSCRIBE;

-- 회원
CREATE TABLE MEMBER(
	ID VARCHAR(20) PRIMARY KEY,
    PASSWORD VARCHAR(20),
    EMAIL VARCHAR(50),
    PHONE VARCHAR(13)
);

-- 채널
CREATE TABLE CHANNEL(
	CHANNEL_CODE INT PRIMARY KEY AUTO_INCREMENT,
    CHANNEL_IMG VARCHAR(100),
    CHANNEL_NAME VARCHAR(50),
    ID VARCHAR(20),
    
    FOREIGN KEY(ID) REFERENCES MEMBER(ID)
);

-- 동영상
CREATE TABLE VIDEO(
	VIDEO_CODE INT PRIMARY KEY AUTO_INCREMENT,
    VIDEO_URL VARCHAR(100),
    VIDEO_IMG VARCHAR(100),
    VIDEO_TITLE VARCHAR(80),
    VIDEO_COUNT INT DEFAULT 0,
    VIDEO_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    VIDEO_DESC TEXT,
    CHANNEL_CODE INT,
    
    FOREIGN KEY(CHANNEL_CODE) REFERENCES CHANNEL(CHANNEL_CODE)
);

-- 댓글
CREATE TABLE COMMENT(
	COMMENT_CODE INT PRIMARY KEY AUTO_INCREMENT,
    COMMENT_TEXT TEXT,
    COMMENT_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    ID VARCHAR(20),
    VIDEO_CODE INT,
    PARENT_CODE INT,
    
    FOREIGN KEY(ID) REFERENCES MEMBER(ID),
    FOREIGN KEY(VIDEO_CODE) REFERENCES VIDEO(VIDEO_CODE)
);

-- 구독
CREATE TABLE SUBSCRIBE(
	SUB_CODE INT PRIMARY KEY AUTO_INCREMENT,
    ID VARCHAR(20),
    CHANNEL_CODE INT,
    
    FOREIGN KEY(ID) REFERENCES MEMBER(ID),
    FOREIGN KEY(CHANNEL_CODE) REFERENCES CHANNEL(CHANNEL_CODE)
);

-- 좋아요
CREATE TABLE VIDEO_LIKE(
	LIKE_CODE INT PRIMARY KEY AUTO_INCREMENT,
    ID VARCHAR(20),
    VIDEO_CODE INT,
    
    FOREIGN KEY(ID) REFERENCES MEMBER(ID),
    FOREIGN KEY(VIDEO_CODE) REFERENCES VIDEO(VIDEO_CODE)
);

INSERT INTO MEMBER(ID, PASSWORD, EMAIL, PHONE) VALUES('akmu', '1234', 'akmu@gmail.com', '010-0000-0000');
SELECT * FROM MEMBER;

insert into channel(channel_img, channel_name, id) values('http://192.168.10.51:8082/channel/dingo.jpg', '딩고 뮤직', 'akmu');

INSERT INTO CHANNEL(CHANNEL_IMG, CHANNEL_NAME, ID) VALUES('http://192.168.10.51:8082/channel/akmu.jpg', 'AKMU' ,'akmu');
SELECT * FROM CHANNEL;

INSERT INTO VIDEO(VIDEO_URL, VIDEO_IMG, VIDEO_TITLE, VIDEO_DESC, CHANNEL_CODE) 
VALUES('http://192.168.10.51:8082/video/AKMU1.mp4', 'http://192.168.10.51:8082/thumbnail/akmu.webp', 'AKMU - 후라이의 꿈 LIVE CLIP (FESTIVAL ver.)', 'More about AKMU', 1);

INSERT INTO VIDEO(VIDEO_URL, VIDEO_IMG, VIDEO_TITLE, VIDEO_DESC, CHANNEL_CODE) 
VALUES('http://192.168.10.51:8082/video/day6.mp4', 'http://192.168.10.51:8082/thumbnail/day6.webp', 'DAY6(데이식스)의 킬링보이스를 라이브로!', '데이식스의 쇼에 오신것을 환영합니다!', 2);

SELECT * FROM VIDEO
JOIN channel USING(channel_code);

SELECT * FROM VIDEO WHERE VIDEO_CODE = 2;