-- 회원
CREATE TABLE MEMBER(
	ID VARCHAR(20) PRIMARY KEY,
    PASSWORD VARCHAR(20),
    EMAIL VARCHAR(50),
    PHONE VARCHAR(13)
);

-- 채널
CREATE TABLE CHANNEL(
	CHANNEL_CODE INT PRIMARY KEY AUTO_INCREMENT,
    CHANNEL_IMG VARCHAR(100),
    CHANNEL_NAME VARCHAR(50),
    ID VARCHAR(20),
    
    FOREIGN KEY(ID) REFERENCES MEMBER(ID)
);

-- 동영상
CREATE TABLE VIDEO(
	VIDEO_CODE INT PRIMARY KEY AUTO_INCREMENT,
    VIDEO_URL VARCHAR(100),
    VIDEO_IMG VARCHAR(100),
    VIDEO_TITLE VARCHAR(80),
    VIDEO_COUNT INT,
    VIDEO_DATE DATE DEFAULT (CURRENT_DATE),
    VIDEO_DESC TEXT,
    CHANNEL_CODE INT,
    
    FOREIGN KEY(CHANNEL_CODE) REFERENCES CHANNEL(CHANNEL_CODE)
);

-- 댓글
CREATE TABLE COMMENT(
	COMMENT_CODE INT PRIMARY KEY AUTO_INCREMENT,
    COMMENT_TEXT TEXT,
    COMMENT_DATE DATE DEFAULT (CURRENT_DATE),
    ID VARCHAR(20),
    VIDEO_CODE INT,
    PARENT_CODE INT,
    
    FOREIGN KEY(ID) REFERENCES MEMBER(ID),
    FOREIGN KEY(VIDEO_CODE) REFERENCES VIDEO(VIDEO_CODE)
);

-- 구독
CREATE TABLE SUBSCRIBE(
	SUB_CODE INT PRIMARY KEY AUTO_INCREMENT,
    ID VARCHAR(20),
    CHANNEL_CODE INT,
    
    FOREIGN KEY(ID) REFERENCES MEMBER(ID),
    FOREIGN KEY(CHANNEL_CODE) REFERENCES CHANNEL(CHANNEL_CODE)
);

-- 좋아요
CREATE TABLE VIDEO_LIKE(
	LIKE_CODE INT PRIMARY KEY AUTO_INCREMENT,
    ID VARCHAR(20),
    VIDEO_CODE INT,
    
    FOREIGN KEY(ID) REFERENCES MEMBER(ID),
    FOREIGN KEY(VIDEO_CODE) REFERENCES VIDEO(VIDEO_CODE)
);