/*
	ALTER
    - 객체를 수정하는 구문
    
    ALTER TABLE 테이블명 수정할내용;
*/
-- 여기서 사용할 테이블 생성
CREATE TABLE DEPT_COPY
SELECT * FROM KH.DEPARTMENT;

SELECT * FROM DEPT_COPY;

/*
	1. 컬럼을 추가 / 수정 / 삭제 / 이름 변경
    1-1. 컬럼 추가 (ADD)
    ALTER TABLE 테이블명 ADD 컬럼명 자료형 [DEFAULT 기본값];
*/
-- CNAME 컬럼 추가
ALTER TABLE DEPT_COPY ADD CNAME VARCHAR(20);
-- >> 새로운 컬럼이 만들어지고 기본적으로 NULL로 채워짐

-- LNAME 컬럼 추가 (기본값 : 한국)
ALTER TABLE DEPT_COPY ADD LNAME VARCHAR(20) DEFAULT '한국';
-- >> 새로운 컬럼이 만들어지고 지정한 기본값으로 채워짐

/*
	1-2. 컬럼 수정 (MODIFY)
    - 자료형 변경 : ALTER TABLE 테이블명 MODIFY 컬럼명 변경할자료형;
    - 기본값 변경 : ALTER TABLE 테이블명 MODIFY 컬럼명 자료형 DEFAULT 변경할기본값;
	
    * 참고 : DEFAULT 삭제
    ALTER TABLE 테이블명 MODIFY 컬러명 자료형 DEFAULT NULL;
*/
-- DEPT_ID 컬럼의 자료형 CHAR(3)으로 변경
ALTER TABLE DEPT_COPY MODIFY DEPT_ID INT; -- 에러 발생
ALTER TABLE DEPT_COPY MODIFY CNAME INT; -- 기존 데이터가 없으면 자료형 변경 가능

-- DEPT_TITLE의 자료형을 VARCHAR(5)로 변경
ALTER TABLE DEPT_COPY MODIFY DEPT_TITLE VARCHAR(5);
-- >> 변경하려는 자료형의 크기보다 이미 큰 값이 존재하면 에러 발생

-- 다중 수정 가능
-- DEPT_TITLE 컬럼의 자료형은 VARCHAR(40),
-- LOCATION_ID 컬럼의 자료형은 VARCHAR(2),
-- LNAME 컬럼의 기본값을 미국으로 변경 (자료형: VARCHAR(20))
ALTER TABLE DEPT_COPY 
	MODIFY DEPT_TITLE VARCHAR(40),
	MODIFY LOCATION_ID VARCHAR(2),
    MODIFY LNAME VARCHAR(20) DEFAULT '미국';

INSERT INTO DEPT_COPY(DEPT_ID, DEPT_TITLE, LOCATION_ID, CNAME)
VALUES ('D10', '개발부', 'L3', 10);

/*
	1-3. 컬럼 삭제
    
    ALTER TABLE 테이블명 DROP COLUMN 컬럼명;
	
    - 데이터 값이 기록되어 있어도 같이 삭제된다. (삭제된 컬럼 복구는 불가능)
    - 테이블에는 최소 한 개의 컬럼이 존재해야 한다.
    - 참조되고 있는 컬럼이 있다면 삭제가 불가능하다.
*/
ALTER TABLE DEPT_COPY DROP COLUMN DEPT_ID;
ALTER TABLE DEPT_COPY DROP COLUMN DEPT_TITLE;
ALTER TABLE DEPT_COPY DROP COLUMN LOCATION_ID;
ALTER TABLE DEPT_COPY DROP COLUMN CNAME;
ALTER TABLE DEPT_COPY DROP COLUMN LNAME; -- 삭제 불가능

-- MEM_GRADE 테이블의 GRADE_CODE 삭제
ALTER TABLE MEM_GRADE DROP COLUMN GRADE_CODE;
SELECT * FROM MEM_GRADE;

/*
	1-4. 컬럼명 변경 (RENAME COLUMN)
    ALTER TABLE 테이블명 RENAME COLUMN 기존컬럼명 TO 변경할컬럼명;
*/
-- DEPT_COPY 테이블에서 LNAME 컬럼명을 LOCATION_NAME으로 변경
ALTER TABLE DEPT_COPY RENAME COLUMN LNAME TO LOCATION_NAME;

/*
	2. 제약조건 추가 / 삭제
    2-1. 제약조건 추가 (ADD)
    - ADD [CONSTRAINT 제약조건명] PRIMARY KEY(컬럼명);
    - ADD [CONSTRAINT 제약조건명] FOREIGN KEY(컬럼명) REFERENCES 테이블명(컬럼명);
    - ADD [CONSTRAINT 제약조건명] UNIQUE(컬럼명);
    - ADD [CONSTRAINT 제약조건명] CHECK(컬럼에 대한 조건);
    - NOT NULL : MODIFY 컬럼명 [CONSTRAINT 제약조건명] NOT NULL;
*/
DROP TABLE DEPT_COPY;

CREATE TABLE DEPT_COPY
SELECT * FROM KH.DEPARTMENT;

-- DEPT_COPY 테이블의 DEPT_ID 컬럼에 기본키(PK, PRIMARY KEY) 제약조건 추가
ALTER TABLE DEPT_COPY ADD PRIMARY KEY(DEPT_ID);
ALTER TABLE DEPT_COPY ADD CONSTRAINT DEPT_COPY_PK PRIMARY KEY(DEPT_ID);

-- DEPT_TITLE 컬럼에 UNIQUE 제약조건 추가
ALTER TABLE DEPT_COPY ADD UNIQUE(DEPT_TITLE);
ALTER TABLE DEPT_COPY ADD CONSTRAINT DEPT_COPY_UQ UNIQUE(DEPT_TITLE);

/*
	2-2. 제약조건 삭제
    - NOT NULL : ALTER TABLE 테이블명 MODIFY 컬럼명 NULL;
    - PRIMARY KEY : ALTER TABLE 테이블명 DROP PRIMARY KEY;
    - 나머지 : ALTER TABLE 테이블명 DROP CONSTRAINT 제약조건명;
*/
ALTER TABLE DEPT_COPY DROP CONSTRAINT DEPT_COPY_UQ;
ALTER TABLE DEPT_COPY DROP PRIMARY KEY;

-- 제약조건명 확인
SELECT TABLE_SCHEMA, TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_SCHEMA = 'SAMPLE' AND TABLE_NAME = 'DEPT_COPY';

SELECT * FROM DEPT_COPY;
DESC DEPT_COPY;

/*
	3. 테이블명 변경 (RENAME)
    ALTER TALBE 기존테이블명 RENAME TO 변경할테이블명;
*/
-- DEPT_COPY => DEPT_TEST 변경
ALTER TABLE DEPT_COPY RENAME TO DEPT_TEST;

SELECT * FROM DEPT_TEST;

/*
	DROP
    - 객체를 삭제하는 구문
    DROP TABLE 테이블명;
*/
DROP TABLE DEPT_TEST;

-- 삭제하고 싶다면 자식 테이블 먼저 삭제 후 부모 테이블 삭제 가능
DROP TABLE MEMBER;
DROP TABLE MEM_GRADE;

CREATE TABLE MEM_GRADE(
	GRADE_CODE INT PRIMARY KEY AUTO_INCREMENT,
    GRADE_NAME VARCHAR(30) NOT NULL
);

INSERT INTO MEM_GRADE(GRADE_NAME) VALUES('일반회원');
INSERT INTO MEM_GRADE(GRADE_NAME) VALUES('우수회원');
INSERT INTO MEM_GRADE(GRADE_NAME) VALUES('특별회원');

CREATE TABLE MEMBER(
	MEM_NO INT PRIMARY KEY AUTO_INCREMENT, -- 컬럼 레벨 방식
    MEM_ID VARCHAR(20) NOT NULL UNIQUE,
    MEM_PWD VARCHAR(20) NOT NULL,
    MEM_NAME VARCHAR(20) NOT NULL,
    GRADE_ID INT,
    FOREIGN KEY (GRADE_ID) REFERENCES MEM_GRADE(GRADE_CODE) ON DELETE CASCADE -- 테이블 레벨 방식
);

INSERT INTO MEMBER(MEM_ID, MEM_PWD, MEM_NAME, GRADE_ID) 
VALUES('USER01', 'PASS01', '최제환', NULL); -- >> 외래키 제약조건이 부여되도 기본적으로 NULL 허용
INSERT INTO MEMBER(MEM_ID, MEM_PWD, MEM_NAME, GRADE_ID) 
VALUES('USER02', 'PASS02', '김경주', 1);
INSERT INTO MEMBER(MEM_ID, MEM_PWD, MEM_NAME, GRADE_ID) 
VALUES('USER03', 'PASS03', '우현성', 2);

SELECT * FROM MEMBER;
SELECT * FROM MEM_GRADE;


